/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gilbertomorales.Prova;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author laboratorio
 */
public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblValor = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        lblModelo = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        lblMarca = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        lblFabricacao = new javax.swing.JLabel();
        txtFabricacao = new javax.swing.JTextField();
        lblCombustivel = new javax.swing.JLabel();
        txtCombustivel = new javax.swing.JTextField();
        lblPlaca = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        rdoCarro = new javax.swing.JRadioButton();
        rdoMoto = new javax.swing.JRadioButton();
        lblPortamalas = new javax.swing.JLabel();
        txtPortamalas = new javax.swing.JTextField();
        lblPortas = new javax.swing.JLabel();
        txtPortas = new javax.swing.JTextField();
        lblCilindradas = new javax.swing.JLabel();
        txtCilindradas = new javax.swing.JTextField();
        lblTransmissao = new javax.swing.JLabel();
        txtTransmissao = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCarro = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMoto = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblValor.setText("Valor do veículo");

        txtValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorActionPerformed(evt);
            }
        });

        lblModelo.setText("Modelo");

        txtModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModeloActionPerformed(evt);
            }
        });

        lblMarca.setText("Marca");

        txtMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcaActionPerformed(evt);
            }
        });

        lblFabricacao.setText("Ano fabricação");

        txtFabricacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFabricacaoActionPerformed(evt);
            }
        });

        lblCombustivel.setText("Tipo combustível");

        txtCombustivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCombustivelActionPerformed(evt);
            }
        });

        lblPlaca.setText("Placa");

        txtPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacaActionPerformed(evt);
            }
        });

        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoCarro);
        rdoCarro.setText("Carro");
        rdoCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoCarroActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoMoto);
        rdoMoto.setText("Moto");
        rdoMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoMotoActionPerformed(evt);
            }
        });

        lblPortamalas.setText("Capacidade Porta-malas");

        txtPortamalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPortamalasActionPerformed(evt);
            }
        });

        lblPortas.setText("Número de portas");

        txtPortas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPortasActionPerformed(evt);
            }
        });

        lblCilindradas.setText("Cilindradas");

        txtCilindradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCilindradasActionPerformed(evt);
            }
        });

        lblTransmissao.setText("Tipo da Transmissão");

        txtTransmissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTransmissaoActionPerformed(evt);
            }
        });

        tblCarro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Valor", "Modelo", "Marca", "Ano Fabricação", "Tipo combustível", "Placa", "Capacidade", "Número de portas"
            }
        ));
        jScrollPane1.setViewportView(tblCarro);

        tblMoto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Valor", "Modelo", "Marca", "Ano Fabricação", "Tipo combustível", "Placa", "Cilindradas", "Tipo transmissão"
            }
        ));
        jScrollPane2.setViewportView(tblMoto);

        jLabel1.setText("Gilberto Morales 13.09.24");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPlaca)
                            .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCombustivel)
                            .addComponent(txtCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFabricacao)
                            .addComponent(txtFabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblValor)
                                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblModelo)
                                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMarca)
                                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblPortas)
                                            .addComponent(txtPortas, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblPortamalas)
                                            .addComponent(txtPortamalas, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblTransmissao)
                                            .addComponent(txtTransmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblCilindradas)
                                            .addComponent(txtCilindradas, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rdoCarro)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rdoMoto)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 765, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 765, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lblValor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rdoCarro)
                                    .addComponent(rdoMoto))
                                .addGap(18, 18, 18)
                                .addComponent(lblModelo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblMarca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblPortamalas)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtPortamalas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblPortas)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtPortas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblCilindradas)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtCilindradas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblTransmissao)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtTransmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(lblFabricacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblCombustivel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblPlaca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorActionPerformed

    private void txtModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloActionPerformed

    private void txtMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaActionPerformed

    private void txtFabricacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFabricacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFabricacaoActionPerformed

    private void txtCombustivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCombustivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCombustivelActionPerformed

    private void txtPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if (rdoCarro.isSelected()) {

            Carro c = new Carro(txtValor.getText(), txtModelo.getText(), txtMarca.getText(), txtFabricacao.getText(), txtCombustivel.getText(), txtPlaca.getText(), txtPortamalas.getText(), txtPortas.getText());
            DefaultTableModel tabelaCarro = (DefaultTableModel) tblCarro.getModel();
            
            tabelaCarro.addRow(c.obterDados());
            c.calculaImposto();
            
            
        }
        
        if (rdoMoto.isSelected()) {

            Moto m = new Moto(txtValor.getText(), txtModelo.getText(), txtMarca.getText(), txtFabricacao.getText(), txtCombustivel.getText(), txtPlaca.getText(), txtCilindradas.getText(), txtTransmissao.getText());
            DefaultTableModel tabelaMoto = (DefaultTableModel) tblMoto.getModel();
            
            tabelaMoto.addRow(m.obterDados());
            m.calculaImposto();
            
            
        }

//        if (rdoProfessor.isSelected()) {
//            
//            Professor p = new Professor(txtNome1.getText(), txtNascimento.getText(), sexo, txtCPF.getText(), txtCPF.getText(), txtEndereco.getText(), (String) cmbEstado.getSelectedItem(), txtTelefone.getText(), txtPai.getText(), txtMae.getText(), txtNacionalidade.getText(), txtMatriculaP.getText(), txtCursop.getText(), txtFormacao.getText());
//            DefaultTableModel tabelaProfessor = (DefaultTableModel) tblProfessor1.getModel();
//            tabelaProfessor.addRow(p.obterDados());
//            p.executaAcao();
//            
//        } else if (rdoAluno.isSelected()) {
//            
//            Aluno a = new Aluno(txtNome1.getText(), txtNascimento.getText(), sexo, txtCPF.getText(), txtCPF.getText(), txtEndereco.getText(), (String) cmbEstado.getSelectedItem(), txtTelefone.getText(), txtPai.getText(), txtMae.getText(), txtNacionalidade.getText(), txtMatricula.getText(), txtCurso.getText());
//            DefaultTableModel tabelaAluno = (DefaultTableModel) tblAluno.getModel();
//            tabelaAluno.addRow(a.obterDados());
//            a.executaAcao();
//            
//        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rdoCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoCarroActionPerformed
        // TODO add your handling code here:
        if (rdoCarro.isSelected()) {
            
            txtPortamalas.setVisible(true);
            txtPortas.setVisible(true);
            lblPortamalas.setVisible(true);
            lblPortas.setVisible(true);
            
            txtCilindradas.setVisible(false);
            txtTransmissao.setVisible(false);
            lblCilindradas.setVisible(false);
            lblTransmissao.setVisible(false);     

        }
    }//GEN-LAST:event_rdoCarroActionPerformed

    private void rdoMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoMotoActionPerformed
        // TODO add your handling code here:
        if (rdoMoto.isSelected()) {
            
            txtPortamalas.setVisible(false);
            txtPortas.setVisible(false);
            lblPortamalas.setVisible(false);
            lblPortas.setVisible(false);
            
            txtCilindradas.setVisible(true);
            txtTransmissao.setVisible(true);
            lblCilindradas.setVisible(true);
            lblTransmissao.setVisible(true);     

        }
    }//GEN-LAST:event_rdoMotoActionPerformed

    private void txtPortamalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPortamalasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPortamalasActionPerformed

    private void txtPortasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPortasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPortasActionPerformed

    private void txtCilindradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCilindradasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCilindradasActionPerformed

    private void txtTransmissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTransmissaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTransmissaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCilindradas;
    private javax.swing.JLabel lblCombustivel;
    private javax.swing.JLabel lblFabricacao;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JLabel lblPortamalas;
    private javax.swing.JLabel lblPortas;
    private javax.swing.JLabel lblTransmissao;
    private javax.swing.JLabel lblValor;
    private javax.swing.JRadioButton rdoCarro;
    private javax.swing.JRadioButton rdoMoto;
    private javax.swing.JTable tblCarro;
    private javax.swing.JTable tblMoto;
    private javax.swing.JTextField txtCilindradas;
    private javax.swing.JTextField txtCombustivel;
    private javax.swing.JTextField txtFabricacao;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtPortamalas;
    private javax.swing.JTextField txtPortas;
    private javax.swing.JTextField txtTransmissao;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
